config/routes.rb
Rails.application.routes.draw do

  get 'info/about'

  get 'info/contacts'

  
  resources :pins

  resources :klicks

  resources :runways
  
  resources :users

  root 'pins#index'

   get 'admin', to: 'sessions#new'
   post 'admin', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'

end

app/models/Runway.rb
class Pin < ActiveRecord::Base
	has_attached_file :image, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
  	                ["100x100>", :jpg, :quality => 70],  large:  
  	                ['1000>', :jpg, :quality => 70] }
  	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/concerns/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/models/klick.rb
class Klick < ActiveRecord::Base
	has_attached_file :image, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
  	                ["100x100>", :jpg, :quality => 70],  large:  
  	                ['1000>', :jpg, :quality => 70] }
  	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	has_attached_file :image, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
  	                ["100x100>", :jpg, :quality => 70],  large:  
  	                ['1000>', :jpg, :quality => 70] }
  	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

 def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	#!current_seller.nil?
    !!current_user
  end

  def require_admin
      if (logged_in? && !current_user.admin) || (!logged_in?)
        redirect_to root_path
      end
    end
  end 

app/controllers/info_controller.rb
class InfoController < ApplicationController
  
  def about
  end

  def contacts
  end
end

app/controllers/klicks_controller.rb
class KlicksController < ApplicationController

	before_action :require_admin, except: [:index]

	def index
		@klick = Klick.all.order("created_at DESC")
	end

	def new
		@klick = Klick.new
	end

	def create
		@klick = Klick.new (set_klicks)
			if @klick.save
				redirect_to klicks_path(@klick)
			else
				render 'new'
			end	
	end

	def show
		@klick = Klick.find(params[:id])
	end

	def edit
		@klick = Klick.find(params[:id])
	end

	def update
		@klick = Klick.find(params[:id])
			if @klick.update(set_klicks)
				redirect_to klicks_path
			else
				render 'edit'
			end 
	end

	def destroy
		@klick = Klick.find(params[:id])
			@klick.destroy
			redirect_to klicks_path
	end


	private
		def set_klicks
			params.require(:klick).permit(:name, :image)
		end
	end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

	before_action :require_admin, except: [:index]

	def index
		@pin = Pin.all.order("created_at DESC")
	end

	def new
		@pin = Pin.new
	end

	def create
		@pin = Pin.new (set_pins)
			if @pin.save
				redirect_to pins_path(@Pin)
			else
				render 'new'
			end	
	end

	def show
		@pin = Pin.find(params[:id])
	end

	def edit
		@pin = Pin.find(params[:id])
	end

	def update
		@pin = Pin.find(params[:id])
			if @pin.update(set_pins)
				redirect_to pins_path
			else
				render 'edit'
			end 
	end

	def destroy
		@pin = Pin.find(params[:id])
			@pin.destroy
			redirect_to pins_path
	end


	private
		def set_pins
			params.require(:pin).permit(:name, :image, :image2, :image3)
		end
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

def create
	user = User.find_by(username: params[:session][:username].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id #user signs up
			#flash[:success] = "You have successfully logged in"
			redirect_to root_path
		else
			#flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

def destroy
	session[:user_id] = nil
	#flash[:success] = "You have logged out"
	redirect_to root_path
end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :contact, :destroy]
	before_action :require_admin, except: [:show, :contact]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
			if @user.save
				session[:seller_id] = @seller.id
				redirect_to user_path(@user)
			else
				render 'new'
			end
	end

	def edit
	end

	def update
			if @user.update(user_params)
				redirect_to user_path(@user)
			else
				render 'edit'
			end
	end

	def destroy
		@user.destroy
		redirect_to pins_path
	end

	private
		def user_params
			params.require(:user).permit(:username, :email, :age, :description, :location, :number, :address, :password, :image)
		end
		
		def set_user
			@user = User.find(params[:id])
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/about.html.erb
<body style="background-color:#bababa">
	<div class = "container">
		<div class="jumbotron" style="background-color:#fff;margin-top:10%">
  			<h2 style="color:#969696;font-family: 'SciFly-Sans', sans-serif">About Me</h2>
  				<p style="font-family:GlacialIndifference-Regular;color:#969696">My name is Felix Calis and I am a photograper, brand strategist, marketer, events organizer and entrepreneur. I have established myself in the world of Fashion Photography and have an extensive backgrond in brand development for a number of major ad agencies. I am always looking for an opportunity to showcase my talents to new clients.</p>
  				<p style="font-family:GlacialIndifference-Regular;color:#969696">I have worked with professionals from all over the world which have helped enhance my management skills in addition to my creative talents. I love thinking outside the box and coming up with creative ideas that are innovative and can communicate the brand message to the consumer. I also love travelling and expanding my social circle on a global level.</p>
  				<p style="font-family:GlacialIndifference-Regular;color:#969696">Currently I am building a creative company that takes all my existing interests and skills of branding, event management and photography and incorporates them into one format</p> 
  				<p><%= link_to 'Back', root_path, :class => 'back' %><p>
  		</div>
	</div>
</body>

app/views/info/contacts.html.erb
<body style="background-color:#bababa">
  <div class = "container">
    <div class="jumbotron" style="background-color:#fff;margin-top:10%">
        
        <h1 style="font-family:'SciFly-Sans';color:#969696">CONTACT</h1>
  				
          <h3 style="font-family:'SciFly-Sans';color:#969696">Phone: </h4>
            <p style="font-family:'SciFly-Sans';font-size: 15px">0091-8939693957</p>
  			
        	<h3 style="font-family:'SciFly-Sans';color:#969696">Email: </h4>
           <p style="font-family:'SciFly-Sans';font-size: 17px">felixcalis@gmail.com</p>
  			
        	<h3 style="font-family:'SciFly-Sans';color:#969696">Location: </h4>
          <p style="font-family:'SciFly-Sans';font-size: 17px">Chennai - Paris<br /><br />
  			
        	<p><%= link_to 'Back', root_path, :class => 'back' %><p>
  	</div>
  </div>
</body>

     

app/views/klicks/edit.html.erb
<div class = "container-fluid">
	<h1 style="text-align:center">Edit image</h1>
		<div class = "row">
			<div class = "col-md-6 col-md-offset-3">
				<%= form_for @klick do |l| %>
					<%= l.label :name %>
					<%= l.text_field :name, class: "form-control"%><br /><br />
					
					<%= l.label :image %>
					<%= l.file_field :image, class: "form-control"%><br /><br />
					
					<%= l.submit 'Update Image' %>
				<% end %>
			</div>
		</div>
</div>

app/views/klicks/index.html.erb
<%= render 'layouts/sidebar2' %>
<div class="container-fluid">
<div id="pins" class="transitions-enabled">
  <% @klick.each do |k| %>
   <%= link_to k.image.url(:large), :class => 'fancybox', :rel => 'group' do %>
    <div class="box">
        <%= image_tag k.image.url(:large) %>
       <% if logged_in? && current_user.admin %>
          <%= link_to 'EDIT', edit_klick_path(k), :id => "editpins" %>
          <%= link_to 'DELETE', k, method: :delete,  data: { confirm: 'Are you sure?' }, :id => "editpins" %>
        <% end %>
    </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/klicks/new.html.erb
<div class = "container-fluid">
	<h1 style="text-align:center">Add a new image</h1>
		<div class = "row">
			<div class = "col-md-6 col-md-offset-3">
				<%= form_for @klick do |l| %>
					<%= l.label :name %>
					<%= l.text_field :name, class: "form-control"%><br /><br />
					
					<%= l.label :image %>
					<%= l.file_field :image, class: "form-control"%><br /><br />
				
					<%= l.submit 'Add Image'%>
				<% end %>
			</div>
		</div>
</div>

app/views/layouts/_sidebar.html.erb
<div id="wrapper">
    <div id="sidebar-wrapper"style="background-color: #ffffff">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
            <li><%= link_to 'ABOUT ME', info_about_path, :class => "menu-item" %></li><br />
            <li><%= link_to 'KLICK', info_contacts_path, :class => "menu-item" %></li><br />
            <li><%= link_to 'RUNWAY', info_events_path, :class => "menu-item" %></li><br />
            <li><%= link_to 'CONTACT', info_contacts_path, :class => "menu-item" %></li><br />
            <li><%= link_to image_tag("instagram-icon.png"), 'https://www.instagram.com/felixcalis/' %></li>
            <li><%= link_to image_tag("pinterest-icon.png"), 'https://www.pinterest.com/felixcalis7/'%></li>
            <li><%= link_to image_tag("facebook-icon.png"), 'https://www.facebook.com/felix.calis.7?fref=ts'%></li>

        </ul>
    </div>
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-6">
                            <%= link_to 'FELIX CALIS', root_path, :id => "menu-toggle" %>
                    </div>
                    <div class="col-lg-12 col-md-6">
                            <% if logged_in? && current_user.admin %>
                                <%= link_to 'Logout', logout_path, method: :delete, :class => "menu-toggle2" %>
                                <%= link_to 'Add', new_pin_path, :class => "menu-toggle3" %>
                             <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                        

app/views/layouts/_sidebar2.html.erb
<div id="wrapper">
    <div id="sidebar-wrapper"style="background-color: #ffffff">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
            <li><%= link_to 'HOME', root_path, :class => "menu-item" %></li><br />
            <li><%= link_to 'ABOUT ME', info_about_path, :class => "menu-item" %></li><br />
            <li><%= link_to 'KLICK', klicks_path, :class => "menu-item" %></li><br />
            <li><%= link_to 'RUNWAY', '#', :class => "menu-item" %></li><br />
            <li><%= link_to 'CONTACT', info_contacts_path, :class => "menu-item" %></li><br />
            <li><%= link_to image_tag("instagram-icon.png"), 'https://www.instagram.com/felixcalis/' %></li>
            <li><%= link_to image_tag("pinterest-icon.png"), 'https://www.pinterest.com/felixcalis7/'%></li>
            <li><%= link_to image_tag("facebook-icon.png"), 'https://www.facebook.com/felix.calis.7?fref=ts'%></li>

        </ul>
    </div>
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-6">
                            <%= link_to 'FELIX CALIS', root_path, :id => "menu-toggle" %>
                    </div>
                    <div class="col-lg-12 col-md-6">
                            <% if logged_in? && current_user.admin %>
                                <%= link_to 'Logout', logout_path, method: :delete, :class => "menu-toggle2" %>
                                <%= link_to 'Add', new_klick_path, :class => "menu-toggle3" %>
                             <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FelixCalis</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/pins/edit.html.erb
<div class = "container-fluid">
	<h1 style="text-align:center">Edit image</h1>
		<div class = "row">
			<div class = "col-md-6 col-md-offset-3">
				<%= form_for @pin do |l| %>
				<%= l.label :name %>
					<%= l.text_field :name, class: "form-control"%><br /><br />
					
					<%= l.label :image %>
					<%= l.file_field :image, class: "form-control"%><br /><br />
					<%= l.submit 'Update Image' %>
				<% end %>
			</div>
		</div>
</div>

app/views/pins/index.html.erb
<%= render 'layouts/sidebar' %>
<div class="container-fluid">
<div id="pins" class="transitions-enabled">
  <% @pin.each do |pin| %>
   <%= link_to pin.image.url(:large), :class => 'fancybox', :rel => 'group' do %>
    <div class="box">
        <%= image_tag pin.image.url(:large) %>
       <% if logged_in? && current_user.admin %>
          <%= link_to 'EDIT', edit_pin_path(pin), :id => "editpins" %>
          <%= link_to 'DELETE', pin, method: :delete,  data: { confirm: 'Are you sure?' }, :id => "editpins" %>
        <% end %>
    </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/pins/new.html.erb
<div class = "container-fluid">
	<h1 style="text-align:center">Add a new image</h1>
		<div class = "row">
			<div class = "col-md-6 col-md-offset-3">
				<%= form_for @pin do |l| %>
				<%= l.label :name %>
					<%= l.text_field :name, class: "form-control"%><br /><br />
					
					<%= l.label :image %>
					<%= l.file_field :image, class: "form-control"%><br /><br />
					<%= l.submit 'Add Image'%>
				<% end %>
			</div>
		</div>
</div>

app/views/users/edit.html.erb
<h1 style="text-align:center">Edit User Account</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

			<%= f.label :username  %>
			<%= f.text_field :username, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %><br />

			<%= f.submit 'Edit User' %>
		<% end %>
			<div class="col-xs-4 col-xs-offset-4">
				[ <%= link_to "Cancel", pins_path %> ]
			</div>
	</div>
</div>

app/views/users/new.html.erb
<h1 style="text-align:center">Create a new Account</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

			<%= f.label :username  %>
			<%= f.text_field :username, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
			
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %><br />

			<%= f.submit 'Add User' %>
		<% end %>
			<div class="col-xs-4 col-xs-offset-4">
				[ <%= link_to "Cancel", pins_path %> ]
			</div>
	</div>
</div>